

```{r}
rm(list = ls())
library(Seurat)
library(SeuratObject)
library(Scissor)
```

›
```{r}
ATAD1 <- Read10X(data.dir = "/Users/nemo/scRNA/scRNA seq/ATAD1/")
ATAD2 <- Read10X(data.dir = "/Users/nemo/scRNA/scRNA seq/ATAD2/")
ATAD3 <- Read10X(data.dir = "/Users/nemo/scRNA/scRNA seq/ATAD3/")

NA1 <- Read10X(data.dir = "/Users/nemo/scRNA/scRNA seq/NA1/")
NA2 <- Read10X(data.dir = "/Users/nemo/scRNA/scRNA seq/NA2/")
NA3 <- Read10X(data.dir = "/Users/nemo/scRNA/scRNA seq/NA3/")

```


```{r}
ATAD1 <- Seurat_preprocessing(ATAD1, verbose = F, project = "ATAD1", min.cells = 3, min.features = 100, dims_UMAP = 1:15, dims_Neighbors = 1:15, resolution = 0.5)
ATAD2 <- Seurat_preprocessing(ATAD2, verbose = F, project = "ATAD2", min.cells = 3, min.features = 100, dims_UMAP = 1:15, dims_Neighbors = 1:15, resolution = 0.5)
ATAD3 <- Seurat_preprocessing(ATAD3, verbose = F, project = "ATAD3", min.cells = 3, min.features = 100, dims_UMAP = 1:15, dims_Neighbors = 1:15, resolution = 0.5)

NA1 <- Seurat_preprocessing(NA1, verbose = F, project = "NA1", min.cells = 3, min.features = 100, dims_UMAP = 1:15, dims_Neighbors = 1:15, resolution = 0.5)
NA2 <- Seurat_preprocessing(NA2, verbose = F, project = "NA2", min.cells = 3, min.features = 100, dims_UMAP = 1:15, dims_Neighbors = 1:15, resolution = 0.5)
NA3 <- Seurat_preprocessing(NA3, verbose = F, project = "NA3", min.cells = 3, min.features = 100, dims_UMAP = 1:15, dims_Neighbors = 1:15, resolution = 0.5)

ATAD1[["percent.mt"]] <- PercentageFeatureSet(ATAD1, pattern = "^MT-")
VlnPlot(ATAD1, c("nFeature_RNA", "nCount_RNA", "percent.mt"), pt.size = 0)

ATAD2[["percent.mt"]] <- PercentageFeatureSet(ATAD2, pattern = "^MT-")
VlnPlot(ATAD2, c("nFeature_RNA", "nCount_RNA", "percent.mt"), pt.size = 0)

ATAD3[["percent.mt"]] <- PercentageFeatureSet(ATAD3, pattern = "^MT-")
VlnPlot(ATAD3, c("nFeature_RNA", "nCount_RNA", "percent.mt"), pt.size = 0)

NA1[["percent.mt"]] <- PercentageFeatureSet(NA1, pattern = "^MT-")
VlnPlot(NA1, c("nFeature_RNA", "nCount_RNA", "percent.mt"), pt.size = 0)

NA2[["percent.mt"]] <- PercentageFeatureSet(NA2, pattern = "^MT-")
VlnPlot(NA2, c("nFeature_RNA", "nCount_RNA", "percent.mt"), pt.size = 0)

NA3[["percent.mt"]] <- PercentageFeatureSet(NA3, pattern = "^MT-")
VlnPlot(NA3, c("nFeature_RNA", "nCount_RNA", "percent.mt"), pt.size = 0)

ATAD1 <- subset(ATAD1, percent.mt < 10)
ATAD2 <- subset(ATAD2, percent.mt < 10)
ATAD3 <- subset(ATAD3, percent.mt < 10)

NA1 <- subset(NA1, percent.mt < 10)
NA2 <- subset(NA2, percent.mt < 10)
NA3 <- subset(NA3, percent.mt < 10)

```

```{r}
ATAD1 <- FindVariableFeatures(ATAD1)
ATAD1 <- ScaleData(ATAD1, verbose = FALSE)
ATAD1 <- RunPCA(ATAD1, features = VariableFeatures(ATAD1))
ATAD1 <- RunUMAP(ATAD1, dims = 1:15)
ATAD1 <- FindNeighbors(ATAD1, dims = 1:15)
ATAD1 <- FindClusters(ATAD1, resolution = 0.5)

ATAD2 <- FindVariableFeatures(ATAD2)
ATAD2 <- ScaleData(ATAD2, verbose = FALSE)
ATAD2 <- RunPCA(ATAD2, features = VariableFeatures(ATAD2))
ATAD2 <- RunUMAP(ATAD2, dims = 1:15)
ATAD2 <- FindNeighbors(ATAD2, dims = 1:15)
ATAD2 <- FindClusters(ATAD2, resolution = 0.5)

ATAD3 <- FindVariableFeatures(ATAD3)
ATAD3 <- ScaleData(ATAD3, verbose = FALSE)
ATAD3 <- RunPCA(ATAD3, features = VariableFeatures(ATAD3))
ATAD3 <- RunUMAP(ATAD3, dims = 1:15)
ATAD3 <- FindNeighbors(ATAD3, dims = 1:15)
ATAD3 <- FindClusters(ATAD3, resolution = 0.5)

NA1 <- FindVariableFeatures(NA1)
NA1 <- ScaleData(NA1, verbose = FALSE)
NA1 <- RunPCA(NA1, features = VariableFeatures(NA1))
NA1 <- RunUMAP(NA1, dims = 1:15)
NA1 <- FindNeighbors(NA1, dims = 1:15)
NA1 <- FindClusters(NA1, resolution = 0.5)

NA2 <- FindVariableFeatures(NA2)
NA2 <- ScaleData(NA2, verbose = FALSE)
NA2 <- RunPCA(NA2, features = VariableFeatures(NA2))
NA2 <- RunUMAP(NA2, dims = 1:15)
NA2 <- FindNeighbors(NA2, dims = 1:15)
NA2 <- FindClusters(NA2, resolution = 0.5)

NA3 <- FindVariableFeatures(NA3)
NA3 <- ScaleData(NA3, verbose = FALSE)
NA3 <- RunPCA(NA3, features = VariableFeatures(NA3))
NA3 <- RunUMAP(NA3, dims = 1:15)
NA3 <- FindNeighbors(NA3, dims = 1:15)
NA3 <- FindClusters(NA3, resolution = 0.5)

DimPlot(ATAD1, reduction = 'umap', label = T, label.size = 10)
DimPlot(ATAD2, reduction = 'umap', label = T, label.size = 10)
DimPlot(NA1, reduction = 'umap', label = T, label.size = 10)
DimPlot(NA2, reduction = 'umap', label = T, label.size = 10)
```


```{r}
ATAD1.marker <- FindAllMarkers(ATAD1, only.pos = TRUE)
ATAD2.marker <- FindAllMarkers(ATAD2, only.pos = TRUE)
ATAD3.marker <- FindAllMarkers(ATAD3, only.pos = TRUE)

NA1.marker <- FindAllMarkers(NA1, only.pos = TRUE)
NA2.marker <- FindAllMarkers(NA2, only.pos = TRUE)
NA3.marker <- FindAllMarkers(NA3, only.pos = TRUE)

library(dplyr)
top30.ATAD1 <- ATAD1.marker %>% group_by(cluster) %>% top_n(30, wt=avg_log2FC)
top30.ATAD2 <- ATAD2.marker %>% group_by(cluster) %>% top_n(30, wt=avg_log2FC)
top30.ATAD3 <- ATAD3.marker %>% group_by(cluster) %>% top_n(30, wt=avg_log2FC)

top30.NA1 <- NA1.marker %>% group_by(cluster) %>% top_n(30, wt=avg_log2FC)
top30.NA2 <- NA2.marker %>% group_by(cluster) %>% top_n(30, wt=avg_log2FC)
top30.NA3 <- NA3.marker %>% group_by(cluster) %>% top_n(30, wt=avg_log2FC)

save(ATAD1.marker, file = "ATAD1.marker.Rdata")
save(ATAD2.marker, file = "ATAD2.marker.Rdata")
save(ATAD3.marker, file = "ATAD3.marker.Rdata")

save(NA1.marker, file = "NA1.marker.Rdata")
save(NA2.marker, file = "NA2.marker.Rdata")
save(NA3.marker, file = "NA3.marker.Rdata")

save(top30.ATAD1, file = "top30ATAD1.Rdata")
save(top30.ATAD2, file = "top30ATAD2.Rdata")
save(top30.ATAD3, file = "top30ATAD3.Rdata")

save(top30.NA1, file = "top30NA1.Rdata")
save(top30.NA2, file = "top30NA2.Rdata")
save(top30.NA3, file = "top30NA3.Rdata")
```


```{r}
ATAD1 <- subset(ATAD1, idents="6", invert=TRUE)
new.cluster.ids <- c("Macrophage", "Macrophage", "Monocyte", "Macrophage", "T", "Macrophage", "Mast cell", "Mesenchymal cell")
names(new.cluster.ids) <- levels(ATAD1)
ATAD1 <- RenameIdents(ATAD1, new.cluster.ids)
ATAD1[["ann"]] <- Idents(ATAD1)

ATAD2 <- subset(ATAD2, idents="4", invert=TRUE)
new.cluster.ids <- c("Macrophage", "Macrophage", "T", "Monocyte", "Mesenchymal cell", "Macrophage",  "Macrophage", "NK cell", "B cell")
names(new.cluster.ids) <- levels(ATAD2)
ATAD2 <- RenameIdents(ATAD2, new.cluster.ids)
ATAD2[["ann"]] <- Idents(ATAD2)

NA1 <- subset(NA1, idents="7", invert=TRUE)
new.cluster.ids <- c("T", "Monocyte", "Macrophage", "Macrophage", "Mesenchymal cell", "Mesenchymal cell", "Proliferative cell", "Macrophage",  "B cell", "B cell", "Mast cell", "Mesothelial cell", "B cell")
names(new.cluster.ids) <- levels(NA1)
NA1 <- RenameIdents(NA1, new.cluster.ids)
NA1[["ann"]] <- Idents(NA1)


NA2 <- subset(NA2, idents="12", invert=TRUE)
new.cluster.ids <- c("T", "Mesenchymal cell", "Mesenchymal cell", "Mesenchymal cell", "Macrophage", "Monocyte",  "Macrophage", "B cell", "Endothelial cell", "Monocyte",  "Proliferative cell", "Mast cell", "T cell")
names(new.cluster.ids) <- levels(NA2)
NA2 <- RenameIdents(NA2, new.cluster.ids)
NA2[["ann"]] <- Idents(NA2)

```


```{r}
save(ATAD1, file = "ATAD1.Rdata")
save(ATAD2, file = "ATAD2.Rdata")
save(ATAD3, file = "ATAD3.Rdata")
save(NA1, file = "NA1.Rdata")
save(NA2, file = "NA2.Rdata")
save(NA3, file = "NA3.Rdata")

load("ATAD1.Rdata")
load("ATAD2.Rdata")
load("ATAD3.Rdata")
load("NA1.Rdata")
load("NA2.Rdata")
load("NA3.Rdata")
```


```{r}
plan("multiprocess", workers=20)
options(future.globals.maxSize = 50000 * 1024^2)

sc.list <- list(ATAD1=ATAD1, ATAD2=ATAD2, ATAD3=ATAD3, NA1=NA1, NA2=NA2, NA3=NA3)
sc.anchors <- FindIntegrationAnchors(object.list = sc.list, 
                                     normalization.method = "LogNormalize",
                                     scale = FALSE, reference = c(3,4))
sc <- IntegrateData(anchorset = sc.anchors, normalization.method = "LogNormalize")
save(sc.anchors, file = 'sc.anchors.Rdata')
save(sc, file = 'sc.Rdata')
```


```{r}
load("sc.Rdata")

DefaultAssay(sc) <- "integrated"
DefaultAssay(sc) <- "RNA"

sc <- ScaleData(sc, verbose = FALSE)
sc <- RunPCA(sc, verbose = FALSE)
sc <- RunUMAP(sc, dims = 1:15)
sc <- FindNeighbors(sc, dims = 1:15)
sc <- FindClusters(sc, resolution = 0.5)

sc <- subset(sc, idents=c("7","9"), invert=TRUE)
new.cluster.ids <- c("Macrophage", "Mesenchymal cell", "T cell", "Macrophage", "Monocyte",  "NK cell", "B cell",  "Proliferative cell", "B cell")
names(new.cluster.ids) <- levels(sc)
sc <- RenameIdents(sc, new.cluster.ids)
sc[["ann"]] <- Idents(sc)

DimPlot(sc, reduction = 'umap', label = T, label.size = 3)
DimPlot(sc, reduction = 'umap', label = T, label.size = 1, group.by = "orig.ident")

sc.marker <- FindAllMarkers(sc, only.pos = T)
top30_sc.marker <- sc.marker %>% group_by(cluster) %>% top_n(30, wt = avg_log2FC)

save(sc, file="sc.Rdata")
save(sc.marker, file = "sc.marker.Rdata")
save(top30_sc.marker, file = "top30scMarker.Rdata")

```


```{r}
bulk2 <- read.table(file = "./GSE52093_series_matrix.txt", header = TRUE)
save(bulk2, file = "bulk2.Rdata")
```


```{r}
head(bulk2)

library(illuminaHumanv4.db)

Gene <- data.frame(Gene=unlist(mget(x = bulk2$ID_REF[3:nrow(bulk2)], envir = illuminaHumanv4SYMBOL)))
Phenotype2 <- bulk2[1:2,]
bulk2 <- bulk2[3:nrow(bulk2),]
bulk2$Gene <- Gene$Gene

library(dplyr)
bulk2 <- na.omit(bulk2)
bulk2 <- bulk2 %>% distinct(Gene, .keep_all = TRUE)
rownames(bulk2) <- bulk2$Gene
bulk_dataset <- bulk2[,2:(ncol(bulk2)-1)]
bulk_dataset <- normalize.quantiles(bulk_dataset)
bulk_dataset <- as.matrix(bulk_dataset)

Aorta <- as.character(Phenotype2[1,2:ncol(Phenotype2)])
Aorta[which(Aorta=="Aorta dissected")]="1"
Aorta[which(Aorta=="Aorta normal")]="0"
Aorta <- as.numeric(Aorta)
names(Aorta) <- colnames(bulk_dataset)
table(Aorta)
Aorta
tag <- c("dissected", "normal")

infos <- Scissor(bulk_dataset = bulk2, sc_dataset = sc, phenotype = Aorta_1, 
                 tag = tag, alpha = 0.5, family = "binomial", 
                 Save_file = "sc_scissor_alpha0.5.Rdata")

infos <- Scissor(bulk_dataset = bulk2, sc_dataset = sc, phenotype = Aorta_2, 
                 tag = tag, alpha = 0.05, family = "binomial", 
                 Save_file = "sc_scissor_alpha0.05.Rdata")

Scissor_select <- rep("Background cell", ncol(sc))
names(Scissor_select) <- colnames(sc)
Scissor_select[infos$Scissor_pos] <- "Scissor+ cell"
Scissor_select[infos$Scissor_neg] <- "Scissor- cell"

length(infos$Scissor_pos)
length(infos$Scissor_neg)


```

